In [ ]:
# Experiment 12 - Categorical Data Analysis Using Python
# Name: Rachit Jajoo
# PRN: 25070123088
# Batch: ENTC - B1

In [ ]:
# 1. Nominal Data
# Categories without any order
# Example: Gender, Blood Group, Department

# 2. Ordinal Data
# Categories with a meaningful order or rank
# Example: Education Level (High School, Bachelor's, Master's, PhD), Rating (Good, Better, Best)

In [1]:
# Dataset 1 - Code 1: Uploading the data
import pandas as pd
df = pd.read_csv("/content/Expt11.csv")
df

   Student  Gender  Department Grade
0       S1    Male         CSE     A
1       S2  Female          IT     B
2       S3  Female         CSE     A
3       S4    Male         ECE     C
4       S5    Male          IT     B
5       S6  Female         CSE     A
6       S7    Male  Mechanical     B
7       S8  Female          IT     A
8       S9    Male         CSE     C
9      S10  Female         ECE     B
10     S11    Male         CSE     A
11     S12  Female          IT     B
12     S13    Male  Mechanical     C
13     S14  Female         CSE     A
14     S15    Male          IT     B
15     S16  Female         ECE     A
16     S17    Male         CSE     B
17     S18  Female          IT     C
18     S19    Male  Mechanical     B
19     S20  Female         CSE     A
20     S21    Male         ECE     C
21     S22  Female          IT     B
22     S23    Male         CSE     A
23     S24  Female  Mechanical     B
24     S25    Male          IT     A
25     S26  Female         CSE     C
26     S27    Male         ECE     B
27     S28  Female          IT     A
28     S29    Male  Mechanical     C
29     S30  Female         CSE     B
30     S31    Male          IT     A
31     S32  Female         ECE     B
32     S33    Male         CSE     A
33     S34  Female  Mechanical     C
34     S35    Male          IT     B
35     S36  Female         CSE     A
36     S37    Male         ECE     B
37     S38  Female          IT     C
38     S39    Male  Mechanical     B
39     S40  Female         CSE     A
40     S41    Male          IT     B
41     S42  Female         ECE     A
42     S43    Male         CSE     C
43     S44  Female  Mechanical     B
44     S45    Male          IT     A
45     S46  Female         CSE     B
46     S47    Male         ECE     C
47     S48  Female          IT     A
48     S49    Male  Mechanical     B
49     S50  Female         CSE     A
50     S51    Male          IT     B
51     S52  Female         ECE     C
52     S53    Male         CSE     A
53     S54  Female  Mechanical     B
54     S55    Male          IT     C
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [2]:
# Dataset 1 - Code 2: Counting the number of students in each grade.
# Our task is majorly figuring out how to categorize the students based on their grades.
print(df['Grade'].value_counts())

Grade
B    24
A    22
C    14
Name: count, dtype: int64

In [3]:
# Dataset 1 - Code 3: Finding out the number of students in each department
# Our task is to give a headcount of the number of students in each department.
print(df['Department'].value_counts())

Department
CSE           20
IT            18
ECE           11
Mechanical    11
Name: count, dtype: int64

In [7]:
# Dataset 1 - Code 4: Percentage Distribution of grades
# Our task is to find the percentage of students getting grades of which type.
print(df['Grade'].value_counts(normalize=True)*100)

Grade
B    40.000000
A    36.666667
C    23.333333
Name: proportion, dtype: float64

In [ ]:
# Dataset 1 - Code 5: Categorizing the people on basis of their gender
print("Gender Count")
print(df['Gender'].value_counts())

In [6]:
# Dataset 1 - Code 6: Gender vs Grade analysis
print(pd.crosstab(df['Gender'], df['Grade']))

Grade    A   B  C
Gender
Female  14  11  5
Male     8  13  9

In [8]:
# Dataset 1 - Code 7: Department vs Gender
print(pd.crosstab(df['Department'], df['Gender']))

Gender      Female  Male
Department
CSE             12     8
ECE              5     6
IT               9     9
Mechanical       4     7

In [9]:
# Dataset 1 - Code 8: Department vs Grade
print(pd.crosstab(df['Department'], df['Grade']))

Grade        A  B  C
Department
CSE         13  4  3
ECE          2  5  4
IT           7  8  3
Mechanical   0  7  4

In [11]:
# Dataset 1 - Code 9: Department vs Grade Percentage
print(pd.crosstab(df['Department'], df['Grade'], normalize='index')*100)

Grade               A          B          C
Department
CSE         65.000000  20.000000  15.000000
ECE         18.181818  45.454545  36.363636
IT          38.888889  44.444444  16.666667
Mechanical   0.000000  63.636364  36.363636

# Some important theory: Normalization in pd.crosstab

The `normalize` parameter in `pandas.crosstab()` is used to display proportions or percentages instead of raw counts. Here's how its common values work:

*   **`normalize=True` (or `normalize='all'`)**:
    *   Normalizes the entire table by the grand total. Each value in the table represents the proportion of that specific combination relative to *all observations*. The sum of all cells will be 1 (or 100% if multiplied by 100).
    *   **Example:** "What percentage of *all students* are Male and received a Grade 'A'?"

*   **`normalize='index'`**:
    *   Normalizes each row independently by its row sum. Each value represents the proportion relative to its *respective row total*. The sum of values across each row will be 1 (or 100% if multiplied by 100).
    *   **Example:** "*Among all students in the CSE Department*, what percentage received a Grade 'A'?" or "*Among all Female students*, what percentage received a Grade 'B'?"

In [12]:
# Dataset 1 - Code 10: Grouping Data
print(df.groupby('Department')['Grade'].value_counts())

Department  Grade
CSE         A        13
            B         4
            C         3
ECE         B         5
            C         4
            A         2
IT          B         8
            A         7
            C         3
Mechanical  B         7
            C         4
Name: count, dtype: int64

In [14]:
# Dataset 2 - Code 1: Uploading the data
data = {
'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8','O9','O10'],

'Category':['Electronics','Clothing','Electronics','Grocery','Clothing',
            'Electronics','Grocery','Clothing','Electronics','Grocery'],

'Payment_Method':['UPI','Card','UPI','Cash','Card',
                  'UPI','Cash','Card','UPI','Cash'],

'Delivery_Type':['Express','Standard','Express','Standard','Express',
                 'Standard','Express','Standard','Express','Standard'],

'Customer_Type':['New','Returning','Returning','New','Returning',
                 'New','Returning','New','Returning','New']
}

df = pd.DataFrame(data)
df

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       O1  Electronics            UPI       Express           New
1       O2     Clothing           Card      Standard     Returning
2       O3  Electronics            UPI       Express     Returning
3       O4      Grocery           Cash      Standard           New
4       O5     Clothing           Card       Express     Returning
5       O6  Electronics            UPI      Standard           New
6       O7      Grocery           Cash       Express     Returning
7       O8     Clothing           Card      Standard           New
8       O9  Electronics            UPI       Express     Returning
9      O10      Grocery           Cash      Standard           New

In [15]:
# Dataset 2 - Code 2: Counting items purchased per category
print(df['Category'].value_counts())

Category
Electronics    4
Clothing       3
Grocery        3
Name: count, dtype: int64

In [17]:
# Dataset 2 - Code 3: Frequency for Payment Methods
print(df['Payment_Method'].value_counts())

Payment_Method
UPI     4
Card    3
Cash    3
Name: count, dtype: int64

In [18]:
# Dataset 2 - Code 4: Percentage distribution
print(df['Payment_Method'].value_counts(normalize=True)*100)

Payment_Method
UPI     40.0
Card    30.0
Cash    30.0
Name: proportion, dtype: float64

In [19]:
# Dataset 2 - Code 5: Orders from electronics category
electronics_orders = df[df['Category']=='Electronics']
print(electronics_orders)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       O1  Electronics            UPI       Express           New
2       O3  Electronics            UPI       Express     Returning
5       O6  Electronics            UPI      Standard           New
8       O9  Electronics            UPI       Express     Returning

In [20]:
# Dataset 2 - Code 6: Sorting the data
sorted_data = df.sort_values(by='Category')
print(sorted_data)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
1       O2     Clothing           Card      Standard     Returning
4       O5     Clothing           Card       Express     Returning
7       O8     Clothing           Card      Standard           New
0       O1  Electronics            UPI       Express           New
2       O3  Electronics            UPI       Express     Returning
5       O6  Electronics            UPI      Standard           New
8       O9  Electronics            UPI       Express     Returning
3       O4      Grocery           Cash      Standard           New
6       O7      Grocery           Cash       Express     Returning
9      O10      Grocery           Cash      Standard           New

In [21]:
# Dataset 2 - Code 7: Display all unique categories
print(df['Category'].unique())

['Electronics' 'Clothing' 'Grocery']

In [22]:
# Dataset 2 - Code 8: Number of unique values
print(df['Category'].nunique())

3

In [23]:
# Dataset 2 - Code 9: Category vs payment method
print(pd.crosstab(df['Category'],df['Payment_Method']))

Payment_Method  Card  Cash  UPI
Category
Clothing           3     0    0
Electronics        0     0    4
Grocery            0     3    0

In [24]:
# Dataset 2 - Code 10: Grouping orders by category and payment method
print(df.groupby(['Category','Payment_Method']).value_counts())

Category     Payment_Method  Order_ID  Delivery_Type  Customer_Type
Clothing     Card            O2        Standard       Returning        1
                             O5        Express        Returning        1
                             O8        Standard       New              1
Electronics  UPI             O1        Express        New              1
                             O3        Express        Returning        1
                             O6        Standard       New              1
                             O9        Express        Returning        1
Grocery      Cash            O10       Standard       New              1
                             O4        Standard       New              1
                             O7        Express        Returning        1
Name: count, dtype: int64