In [ ]:
# Experiment No. 11 - Create Dataset and Load Dataset
# Name: Rachit Jajoo
# PRN: 25070123088
# Batch: ENTC - B1

In [7]:
# Code 1: Dataset creation
import pandas as pd
data = {
    "Roll Number": [101,102,103,104,105],
    "Gender": ["Male","Female","Female","Male","Male"],
    "Department": ["Computer Science", "IT", "ENTC", "Mechanical", "Computer Science"],
    "CGPA": [8.2,7.5,9.1,6.8,8.7]
}

df = pd.DataFrame(data)
df.to_csv("student_data.csv", index=False)
print(df)
df

   Roll Number  Gender        Department  CGPA
0          101    Male  Computer Science   8.2
1          102  Female                IT   7.5
2          103  Female              ENTC   9.1
3          104    Male        Mechanical   6.8
4          105    Male  Computer Science   8.7

   Roll Number  Gender        Department  CGPA
0          101    Male  Computer Science   8.2
1          102  Female                IT   7.5
2          103  Female              ENTC   9.1
3          104    Male        Mechanical   6.8
4          105    Male  Computer Science   8.7

In [12]:
# Code 2: To perform operations in Panda library
# Just learning some new commands in dataframe
df.shape
df.size
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Roll Number  5 non-null      int64
 1   Gender       5 non-null      object
 2   Department   5 non-null      object
 3   CGPA         5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [10]:
# Code 3: To describe the dataset
df.describe()

       Roll Number     CGPA
count     5.000000  5.00000
mean    103.000000  8.06000
std       1.581139  0.92358
min     101.000000  6.80000
25%     102.000000  7.50000
50%     103.000000  8.20000
75%     104.000000  8.70000
max     105.000000  9.10000

In [35]:
# Code 4: To upload a dataset
import pandas as pd
import numpy as np
df = pd.read_csv("Cars93.csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
5,Buick,Century,Midsize,15.7,22,Driver only,110,6,28.0,16.0
6,Buick,LeSabre,Large,20.8,19,Driver only,170,6,30.5,17.0
7,Buick,Roadmaster,Large,23.7,16,Driver only,180,6,30.5,21.0
8,Buick,Riviera,Midsize,26.3,19,Driver only,170,5,26.5,14.0
9,Cadillac,DeVille,Large,34.7,16,Driver only,200,6,35.0,18.0
10,Cadillac,Seville,Midsize,40.1,16,Driver & Passenger,295,5,31.0,14.0
11,Chevrolet,Cavalier,Compact,13.4,25,NaN,110,5,25.0,13.0
12,Chevrolet,Corsica,Compact,11.4,25,Driver only,110,5,26.0,14.0
13,Chevrolet,Camaro,Sporty,15.1,19,Driver & Passenger,160,4,25.0,13.0
14,Chevrolet,Lumina,Midsize,15.9,21,NaN,110,6,28.5,16.0
15,Chevrolet,Lumina_APV,Van,16.3,18,NaN,170,7,30.5,NaN
16,Chevrolet,Astro,Van,16.6,15,NaN,165,8,33.5,NaN
17,Chevrolet,Caprice,Large,18.8,17,Driver only,170,6,29.5,20.0
18,Chevrolet,Corvette,Sporty,38.0,17,Driver only,300,2,NaN,NaN
19,Chrylser,Concorde,Large,18.4,20,Driver & Passenger,153,6,31.0,15.0
20,Chrysler,LeBaron,Compact,15.8,23,Driver & Passenger,141,6,30.5,14.0
21,Chrysler,Imperial,Large,29.5,20,Driver only,147,6,36.0,17.0
22,Dodge,Colt,Small,9.2,29,NaN,92,5,26.5,11.0
23,Dodge,Shadow,Small,11.3,23,Driver only,93,5,26.5,13.0
24,Dodge,Spirit,Compact,13.3,22,Driver only,100,6,30.5,14.0
25,Dodge,Caravan,Van,19.0,17,Driver only,142,7,26.5,NaN
26,Dodge,Dynasty,Midsize,15.6,21,Driver only,100,6,30.5,16.0
27,Dodge,Stealth,Sporty,25.8,18,Driver only,300,4,20.0,11.0
28,Eagle,Summit,Small,12.2,29,NaN,92,5,26.5,11.0
29,Eagle,Vision,Large,19.3,20,Driver & Passenger,214,6,30.0,15.0
30,Ford,Festiva,Small,7.4,31,NaN,63,4,26.0,12.0
31,Ford,Escort,Small,10.1,23,NaN,127,5,28.0,12.0
32,Ford,Tempo,Compact,11.3,22,NaN,96,5,27.5,13.0
33,Ford,Mustang,Sporty,15.9,22,Driver only,105,4,24.0,12.0
34,Ford,Probe,Sporty,14.0,24,Driver only,115,4,23.0,18.0
35,Ford,Aerostar,Van,19.9,15,Driver only,145,7,30.0,NaN
36,Ford,Taurus,Midsize,20.2,21,Driver only,140,5,27.5,18.0
37,Ford,Crown_Victoria,Large,20.9,18,Driver only,190,6,30.0,21.0
38,Geo,Metro,Small,8.4,46,NaN,55,4,27.5,10.0
39,Geo,Storm,Sporty,12.5,30,Driver only,90,4,24.5,11.0
40,Honda,Prelude,Sporty,19.8,24,Driver & Passenger,160,4,23.5,8.0
41,Honda,Civic,Small,12.1,42,Driver only,102,4,28.0,12.0
42,Honda,Accord,Compact,17.5,24,Driver & Passenger,140,4,28.0,14.0
43,Hyundai,Excel,Small,8.0,29,NaN,81,5,26.0,11.0
44,Hyundai,Elantra,Small,10.0,22,NaN,124,5,28.0,12.0
45,Hyundai,Scoupe,Sporty,10.0,26,NaN,92,4,23.5,9.0
46,Hyundai,Sonata,Midsize,13.9,20,NaN,128,5,31.0,14.0
47,Infiniti,Q45,Midsize,47.9,17,Driver only,278,5,29.0,15.0
48,Lexus,ES300,Midsize,28.0,18,Driver only,185,5,27.5,14.0
49,Lexus,SC300,Midsize,35.2,18,Driver & Passenger,225,4,25.0,9.0
50,Lincoln,Continental,Midsize,34.3,17,Driver & Passenger,160,6,30.0,19.0
51,Lincoln,Town_Car,Large,36.1,18,Driver & Passenger,210,6,31.5,22.0
52,Mazda,323,Small,8.3,29,NaN,82,4,27.0,16.0
53,Mazda,Protege,Small,11.6,28,NaN,103,5,26.5,13.0
54,Mazda,626,Compact,16.5,26,Driver only,164,5,29.5,14.0
55,Mazda,MPV,Van,19.1,18,NaN,155,7,27.5,NaN
56,Mazda,RX-7,Sporty,32.5,17,Driver only,255,2,NaN,NaN
57,Mercedes-Benz,190E,Compact,31.9,20,Driver only,130,5,26.0,12.0
58,Mercedes-Benz,300E,Midsize,61.9,19,Driver & Passenger,217,5,27.0,15.0
59,Mercury,Capri,Sporty,14.1,23,Driver only,100,4,19.0,6.0
60,Mercury,Cougar,Midsize,14.9,19,NaN,140,5,28.0,15.0
61,Mitsubishi,Mirage,Small,10.3,29,NaN,92,5,26.0,11.0
62,Mitsubishi,Diamante,Midsize,26.1,18,Driver only,202,5,27.5,14.0
63,Nissan,Sentra,Small,11.8,29,Driver only,110,5,26.0,12.0
64,Nissan,Altima,Compact,15.7,24,Driver only,150,5,28.5,14.0
65,Nissan,Quest,Van,19.1,17,NaN,151,7,27.0,NaN
66,Nissan,Maxima,Midsize,21.5,21,Driver only,160,5,28.5,14.0
67,Oldsmobile,Achieva,Compact,13.5,24,NaN,155,5,28.0,14.0
68,Oldsmobile,Cutlass_Ciera,Midsize,16.3,23,Driver only,110,5,28.0,16.0
69,Oldsmobile,Silhouette,Van,19.5,18,NaN,170,7,30.5,NaN
70,Oldsmobile,Eighty-Eight,Large,20.7,19,Driver only,170,6,31.5,17.0
71,Plymouth,Laser,Sporty,14.4,23,NaN,92,4,24.5,8.0
72,Pontiac,LeMans,Small,9.0,31,NaN,74,4,25.5,17.0
73,Pontiac,Sunbird,Compact,11.1,23,NaN,110,5,25.0,13.0
74,Pontiac,Firebird,Sporty,17.7,19,Driver & Passenger,160,4,25.0,13.0
75,Pontiac,Grand_Prix,Midsize,18.5,19,NaN,200,5,28.5,16.0
76,Pontiac,Bonneville,Large,24.4,19,Driver & Passenger,170,6,30.5,18.0
77,Saab,900,Compact,28.7,20,Driver only,140,5,26.5,14.0
78,Saturn,SL,Small,11.1,28,Driver only,85,5,26.5,12.0
79,Subaru,Justy,Small,8.4,33,NaN,73,4,23.5,10.0
80,Subaru,Loyale,Small,10.9,25,NaN,90,5,27.5,15.0
81,Subaru,Legacy,Compact,19.5,23,Driver only,130,5,27.0,14.0
82,Suzuki,Swift,Small,8.6,39,NaN,70,4,27.5,10.0
83,Toyota,Tercel,Small,9.8,32,Driver only,82,5,24.0,11.0
84,Toyota,Celica,Sporty,18.4,25,Driver only,135,4,23.0,13.0
85,Toyota,Camry,Midsize,18.2,22,Driver only,130,5,28.5,15.0
86,Toyota,Previa,Van,22.7,18,Driver only,138,7,35.0,NaN
87,Volkswagen,Fox,Small,9.1,25,NaN,81,4,26.0,10.0
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [25]:
# Code 4.1 - Operations on uploaded dataset
print(df.size)

930

In [26]:
# Code 4.2 - Operations on uploaded dataset
print(df.shape)

(93, 10)

In [27]:
# Code 4.3 - Operations on uploaded dataset
print(df.describe())

           Price   MPG.city  Horsepower  Passengers  Rear.seat.room  \
count  93.000000  93.000000   93.000000   93.000000       91.000000
mean   19.509677  22.365591  143.827957    5.086022       27.829670
std     9.659430   5.619812   52.374410    1.038979        2.989072
min     7.400000  15.000000   55.000000    2.000000       19.000000
25%    12.200000  18.000000  103.000000    4.000000       26.000000
50%    17.700000  21.000000  140.000000    5.000000       27.500000
75%    23.300000  25.000000  170.000000    6.000000       30.000000
max    61.900000  46.000000  300.000000    8.000000       36.000000

       Luggage.room
count     82.000000
mean      13.890244
std        2.997967
min        6.000000
25%       12.000000
50%       14.000000
75%       15.000000
max       22.000000

In [28]:
# Code 4.4 - Operations on uploaded dataset
print(df.head())

  Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0        Acura  Integra    Small   15.9        25                 NaN
1        Acura   Legend  Midsize   33.9        18  Driver & Passenger
2         Audi       90  Compact   29.1        20         Driver only
3         Audi      100  Midsize   37.7        19  Driver & Passenger
4          BMW     535i  Midsize   30.0        22         Driver only

   Horsepower  Passengers  Rear.seat.room  Luggage.room
0         140           5            26.5          11.0
1         200           5            30.0          15.0
2         172           5            28.0          14.0
3         172           6            31.0          17.0
4         208           4            27.0          13.0

In [29]:
# Code 4.5 - Operations on uploaded dataset
print(df.tail())

   Manufacturer    Model     Type  Price  MPG.city             AirBags  \
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
88         109           7            34.0           NaN
89         134           5            31.5          14.0
90         178           4            26.0          15.0
91         114           5            29.5          14.0
92         168           5            30.0          15.0

In [31]:
# Code 4.6 - Operations on uploaded dataset
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Price', 'MPG.city', 'AirBags',
       'Horsepower', 'Passengers', 'Rear.seat.room', 'Luggage.room'],
      dtype='object')

In [34]:
# Code 4.7 - Operations on uploaded dataset
print(df.sample(5))

   Manufacturer   Model     Type  Price  MPG.city      AirBags  Horsepower  \
66       Nissan  Maxima  Midsize   21.5        21  Driver only         160
71     Plymouth   Laser   Sporty   14.4        23          NaN          92
47     Infiniti     Q45  Midsize   47.9        17  Driver only         278
41        Honda   Civic    Small   12.1        42  Driver only         102
87   Volkswagen     Fox    Small    9.1        25          NaN          81

    Passengers  Rear.seat.room  Luggage.room
66           5            28.5          14.0
71           4            24.5           8.0
47           5            29.0          15.0
41           4            28.0          12.0
87           4            26.0          10.0

In [36]:
# Code 4.8 - Operations on uploaded dataset
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB
None

In [37]:
# Code 4.9 - Operations on uploaded dataset
print(df.dtypes)

Manufacturer       object
Model              object
Type               object
Price             float64
MPG.city            int64
AirBags            object
Horsepower          int64
Passengers          int64
Rear.seat.room    float64
Luggage.room      float64
dtype: object

In [40]:
# Code 4.10 - Operations on uploaded dataset
df.isnull().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [41]:
# Code 4.11 - Operations on uploaded dataset
df.duplicated().sum()

np.int64(0)

In [42]:
# Code 4.12 - Operations on uploaded dataset
df.nunique()

Manufacturer      32
Model             93
Type               6
Price             81
MPG.city          21
AirBags            2
Horsepower        57
Passengers         6
Rear.seat.room    24
Luggage.room      16
dtype: int64